### ISSUE TITLE
Alexa doesn't play movies and tv shows with accents or Ñ in the title

### ISSUE THREAD

**Issue by R91g** [kodi-connect/kodi-connect#153]
Hi Tomas,

Thank you for your amazing integration between Kodi and Alexa.
Last night I discover your integration and followed your steps from https://kodi-connect.github.io/ to set up Kodi Alexa integration.
I registered in your server https://kodiconnect.kislan.sk/ and followed all the steps without problems.
Alexa skill, Lambda function and Kodi addon seem to work well.

I can discover my Kodi instance and setup the device with my Echo, in https://kodiconnect.kislan.sk/devices the device is connected

But when I say a voice command to Alexa nothing happens.
In Alexa apps I have the Kodi device.

Lambda Function Region in AWS is correct I use EU (Ireland) because I'm from Spain and my Echo is configurated in Spanish (ES).

I have another Lambda Function for Hasska (Home Assistant integration) in the region EU (Ireland) and this function works perfects.

Is the integration not operational yet or is there a problem with my configuration or the Spanish language?

Thank you very much.

**Comment by tkislan** [comment]
Do you have your content in Kodi Video library? Or from what source are you trying to play?

**Comment by R91g** [comment]
Hi,
Thank you for support.

My content is in Kodi Video Library but with[ PlexKodiConnect](https://github.com/croneter/PlexKodiConnect) maybe this is the problem?

I tried say Alexa, stop/Alexa, para/Alexa, pause/Alexa, pausa/Alexa, stop Kodi/Alexa, para Kodi... (In english and Spanish)  when a movie is playing but doesn't work

Tomorrow I will tried with a new Kodi with local library without any hacks like PlexKodiConnect

**Comment by R91g** [comment]
Wow it seems that it already works!
I had some routines to stop, pause and resume kodi with the integration of Home Assistant, I forgeted delete them, it is possible that they would interfered

I play/stop/pause/resume a movie or show  with Alexa without problem, that fantastic.

But with some movie or show Kodi don't play the file, for example I say "Alexa, reproduce el Joker" and Alexa say "Obteniendo Joker en Kodi" and play it perfect but with another movie or show like for example "Alexa, reproduce padre no hay más que uno", Alexa say "Obteniendo Padre no hay más que uno en Kodi" but kodi don't play it. Maybe the problem  is with PlexKodiConnect? With the remote I can play it without problems

**Comment by tkislan** [comment]
```
2020-01-21T21:32:26.941119511Z level="INFO" module="tunnel-server" deviceId="<deviceId>2" rpc="{"type":"command","commandType":"searchAndPlay","filter":{"titles":["Capitán América: El primer vengador","Capitán America: El primer Vengador","Capitan America: El Primer Vengador","Capitán América, el vencedor"],"collections":[],"genres":[],"actors":[],"roles":[],"mediaType":"movie","season":null,"episode":null}}" Sending message to kodi
```

I've found this in log .. just posting it here for reference, so I don't loose it.
I'll try and create a test for it, to verify if accents are indeed a problem

**Comment by tkislan** [comment]
But I've quickly checked the PlexKodiConnect addon, and it seems, that it's what might actually be an issue

https://feathub.com/croneter/PlexKodiConnect/+19
There is this feature request, that mentions, that addon should correctly create entries within Kodi's Movie/TvShow libraries .. if this is not happening now, then this Alexa integration won't work with it.

**Comment by R91g** [comment]
> But I've quickly checked the PlexKodiConnect addon, and it seems, that it's what might actually be an issue
> 
> https://feathub.com/croneter/PlexKodiConnect/+19
> There is this feature request, that mentions, that addon should correctly create entries within Kodi's Movie/TvShow libraries .. if this is not happening now, then this Alexa integration won't work with it.

No, PlexKodiConnect puts the movies and show corretly like a Kodi Library normal, you don't see the different, all addon works fine with PlexKodiconnect like subtitules downloader, this issue is very old, you can find the last version in github:
https://github.com/croneter/PlexKodiConnect

In addition, most movies and series play them without problems, however tomorrow I will try without Plexkodiconnect to discard errors with this.

**Comment by rpharrison** [comment]
I can also confirm that Alexa doesn't like playing titles with accented characters i.e. Pokémon. I'm not using any Plex plugins though.

**Comment by R91g** [comment]
> I can also confirm that Alexa doesn't like playing titles with accented characters i.e. Pokémon. I'm not using any Plex plugins though.

I just made a new installation of Kodi and I added my content by smb to the Kodi library and it still fails in movies and tv shows with accents or characters like **Ñ**

**Comment by tkislan** [comment]
Can you please try this new version of addon if it helps?
https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/plugin.video.kodiconnect-0.2.1.zip

**Comment by R91g** [comment]
> Can you please try this new version of addon if it helps?
> https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/plugin.video.kodiconnect-0.2.1.zip

Still not working with  accents or Ñ.

**Comment by tkislan** [comment]
@R91g can you please give some examples of movie titles?
So that I can try it out

**Comment by R91g** [comment]
> @R91g can you please give some examples of movie titles?
> So that I can try it out

The Spanish language uses many accents, there are a lot of translated titles that have them. For example (between [] original title):

- Aladdín (2019) [Aladdin]
- Alita: Ángel del combate (2019) [Alita, Battle Angel]
- Animales fantásticos y dónde encontrarlos (2016) [Fantastic Beasts and Where to Find Them]
- Animales fantásticos: Los crímenes de Grindelwald (2018) [Fantastic Beasts: The Crimes of Grindelwald]
- Cafarnaúm (2018) [Capharnaüm]
- El Camino: Una película de Breaking Bad (2019) [El Camino: A Breaking Bad Movie]
- Capitán América: El primer vengador (2011) [Captain America: The First Avenger]
- Cómo entrenar a tu dragón (2010) [How to Train Your Dragon]
- Érase una vez en… Hollywood (2019) [Once Upon a Time in... Hollywood]

Title in version original with accents for example:

- **Pokémon Detective Pikachu (2019)**
- Le fabuleux destin d'Amélie Poulain (2001)
- Ola de crímenes (2018)
- Padre no hay más que uno (2019)
- ¿Qué te juegas? (2019)
- Yucatán (2018)

I think that Pokémon is with accents in all languages, you can try with this or maybe you can edit the title of one movie with Kodi to put accents

**Comment by R91g** [comment]
This documentation may be helpful:
https://kodi.wiki/view/Add-on_unicode_paths

**Comment by R91g** [comment]
Attached my log trying play Pokémon Detective Pikachu
[kodi.log](https://github.com/kodi-connect/kodi-connect/files/4106517/kodi.log)

In the log Pokémon show as **Pok\xe9mon**

**Comment by tkislan** [comment]
@R91g This seems weird. All of the logs that you've sent actually show, that Addon was able to successfully find the movie (search for "Found Entity" text)  .. so I don't understand, what the problem was in this case .. did it not start playback at all?

**Comment by R91g** [comment]
> @R91g This seems weird. All of the logs that you've sent actually show, that Addon was able to successfully find the movie (search for "Found Entity" text) .. so I don't understand, what the problem was in this case .. did it not start playback at all?

Yes, it found all but with accents didn't start playback

This log entry does not appear when the movie has accents
2020-01-24 03:45:43.026 T:9296   DEBUG: [KodiConnect] Playing movie: Aladdin

Here video (view it whole)
https://youtu.be/xApJXZdZLNg

**Comment by rpharrison** [comment]
I've also tried again to play Pokémon with the new addon version, it appears to recognise it and says "Getting Pokémon from Kodi" but nothing plays. 

[kodi.log](https://github.com/kodi-connect/kodi-connect/files/4111923/kodi.log)

**Comment by tkislan** [comment]
@rpharrison issue in your log was, that you've asked too early .. it takes the addon a few seconds to build up the search index from all the library

@R91g Can you please try this new addon version? I couldn't figure out what is actually happening, except that it crashes somewhere, but there is no log. So I've added some extra error handling, to figure out what's happening.
But bottom line, you were right, that the "Playing movie" log entry is missing, and I just need to figure out why to fix it.

[plugin.video.kodiconnect-0.2.2.zip](https://github.com/kodi-connect/kodi-connect/files/4113496/plugin.video.kodiconnect-0.2.2.zip)

**Comment by tkislan** [comment]
Please disregard the previous comment, as I've managed to find a problem.

There is a new version available (0.2.3)
https://kodi-connect.github.io/#tutorial---addon

or direct link here:
https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/plugin.video.kodiconnect-0.2.3.zip

**Comment by rpharrison** [comment]
I have tried with the 0.2.3 addon to play Pokémon and now the kodi log is producing a definite error of some kind.

2020-01-26 17:02:47.612 T:14691   DEBUG: [KodiConnect] [ERROR] Failed to play entity: 'ascii' codec can't encode character u'\xe9' in position 34: ordinal not in range(128)

I tried to play several times as well as normal titles.

[kodi.log](https://github.com/kodi-connect/kodi-connect/files/4113719/kodi.log)

**Comment by tkislan** [comment]
https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/plugin.video.kodiconnect-0.2.4.zip
Can you try this one please?

**Comment by rpharrison** [comment]
Now it will play after trying several times, Pokémon. It seems like it is taking a few minutes to build the library index before I can use voice commands.

**Comment by R91g** [comment]
> @rpharrison
> https://kodi-connect.s3.eu-central-1.amazonaws.com/kodi-connect-addon/plugin.video.kodiconnect-0.2.4.zip
> Can you try this one please?

With plugin.video.kodiconnect-0.2.4.zip all works perfects, I tried played some movies and tv shows with accents and Ñ and all was played fine
I paired again Kodi device in Alexa app after update the plugin

**Comment by tkislan** [comment]
@rpharrison Building library index takes some time, and that depends on the machine you're running it on. You can actually see the exact times in the log. In your case it's not minutes, but it's around 30 or so seconds .. 

So closing this issue, as it seems that everything should be working as expected .. thank you for the feedback and help with debugging
