### ISSUE TITLE
Beta Test - Invitiation Link for Skill

### ISSUE THREAD

**Issue by yogin2** [kodi-connect/kodi-connect#2]
i have installed updated Kodi Connect but nothing happens. kodi tells me kodi connect is connected but on the alexa site my kodi is not found.

I cannot find Kodi Connect on Alexa Page to add the skill.

**Comment by Cartman1982** [comment]
Yesterday I also had problems with Kodi connect. Then I did the step by step instructions from the beginning, then it worked perfectly again. under Alexa, although no connection is visible, it still processes the commands and starts the movies / series under Kodi

Von meinem iPhone gesendet

**Comment by tkislan** [comment]
https://github.com/kodi-connect/kodi-connect/blob/master/tutorial-alexa/readme.md

**Comment by yogin2** [comment]
Hi Tomas,

Thank you the quick reply.

I have tried to connect again and having trouble with Kod Connect - Connected/Disconnected in Kodi.

I have tried to set up again from the beginning but still keep get this issue.

Can you help please.

Regards,


Yogin  Patel
07944 174158
Yogin2@Hotmail.Com<mailto:Yogin2@Hotmail.Com>


________________________________
