### ISSUE TITLE
externalids in alexa test data

### ISSUE THREAD

**Issue by imduffy15** [kodi-connect/kodi-connect#587]
Hi @tkislan ,

In your test data I see you have a very rich selection of external IDs https://github.com/kodi-connect/kodi-connect/blob/eac028414e8c33d190b5aff1fed44fc08b4614ef/src/api/alexa/__test__/data/find-how-i-met-your-mother.json

When I hook alexa up myself and run a "search for X" command I only get a very limited set of external IDs. Did you have to do something to get such a rich set?

Thanks,
Ian.

**Comment by tkislan** [comment]
Hi,

it is possible, that they have consolidated this a bit, or improved the matching. It is quite some time since I've checked how the responses look like
